<?php
namespace EventBundle\Repository;
/**
 * ParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{

    public function filterEvents($nom)
    {
        $Query = $this->getEntityManager()->createQuery(
            "Select A   from EventBundle:Evenement A where A.titreEvent LIKE :p ")
            ->setParameter('p','%'.$nom.'%');
        return $Query->getResult();
    }


}