<?php
namespace EventBundle\Repository;
/**
 * ParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findParticiaptionsEvent($event,$user){
        $query = $this->getEntityManager()->createQuery("SELECT c FROM EventBundle:Participation c where c.idEvent='$event' and c.username='$user'");
        return $query->getResult();
    }
    public function findMyParticiaptions($user){
        $query = $this->getEntityManager()->createQuery("SELECT c FROM EventBundle:Participation c INNER JOIN EventBundle:Evenement e where c.username='$user' and c.idEvent=e.idEvent ");
        return $query->getResult();
    }
    public function findMyParticiaptionstrier($user){
        $query = $this->getEntityManager()->createQuery("SELECT c FROM EventBundle:Participation c INNER JOIN EventBundle:Evenement e where c.username='$user' and c.idEvent=e.idEvent ORDER BY e.dateDebutEvent ASC ");
        return $query->getResult();
    }
}