<?php

namespace HuntkingdomBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByArray($array){
        $qb= $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.id in (:array)')
            ->setParameter('array',$array);
        return $qb->getQuery()->getResult();
    }

    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM HuntkingdomBundle:Product p
                WHERE p.nom LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
}
